services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    volumes:
      - api-data:/app/data
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
        - type: bind
          source: ~/.influxdb3/data
          target: /var/lib/influxdb3/data
        - type: bind
          source: ~/.influxdb3/plugins
          target: /var/lib/influxdb3/plugin

  influxdb3-explorer:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb3-explorer
    ports:
      - "8888:80"
    volumes:
      - ./.influxdb3-ui/db:/db:rw
      - ./.influxdb3-ui/config:/app-root/config:ro

  grafana:
    image: grafana/grafana:12.4.0-ubuntu
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin12345}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-readings}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:- change-me}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
      - api

volumes:
  grafana_data:
  api-data:
