apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    isDefault: true
    jsonData:
      version: SQL
      dbName: ${INFLUXDB_BUCKET}
      insecureGrpc: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
